"""Type stubs for RustTorch Python bindings.

Covers Tensor/Variable/nn/optim/data ops exposed via PyO3.
Full runtime in the compiled Rust extension (see __init__.py).
"""

from __future__ import annotations

from typing import Any, List, Optional, Tuple, Union

import numpy as np

__version__: str
__author__: str

class Tensor:
    @staticmethod
    def zeros(shape: List[int]) -> Tensor: ...
    @staticmethod
    def ones(shape: List[int]) -> Tensor: ...
    @staticmethod
    def from_numpy(array: np.ndarray) -> Tensor: ...
    def shape(self) -> List[int]: ...
    def ndim(self) -> int: ...
    def numel(self) -> int: ...
    def __repr__(self) -> str: ...

class Variable:
    def __init__(self, data: List[float], shape: List[int], requires_grad: bool = False) -> None: ...
    @staticmethod
    def from_numpy(array: np.ndarray, requires_grad: bool = False) -> Variable: ...
    def shape(self) -> List[int]: ...
    def numel(self) -> int: ...
    def requires_grad(self) -> bool: ...
    def is_leaf(self) -> bool: ...
    def to_list(self) -> List[float]: ...
    def to_numpy(self) -> np.ndarray: ...
    def grad(self) -> Optional[List[float]]: ...
    def grad_numpy(self) -> Optional[np.ndarray]: ...
    def zero_grad(self) -> None: ...
    def backward(self) -> None: ...
    # differentiable ops
    def add(self, other: Variable) -> Variable: ...
    def sub(self, other: Variable) -> Variable: ...
    def mul(self, other: Variable) -> Variable: ...
    def div(self, other: Variable) -> Variable: ...
    def matmul(self, other: Variable) -> Variable: ...
    def relu(self) -> Variable: ...
    def sigmoid(self) -> Variable: ...
    def tanh(self) -> Variable: ...
    def gelu(self) -> Variable: ...
    def sum(self) -> Variable: ...
    def mean(self) -> Variable: ...
    def mul_scalar(self, scalar: float) -> Variable: ...
    def t(self) -> Variable: ...
    def reshape(self, new_shape: List[int]) -> Variable: ...
    def __repr__(self) -> str: ...

class Parameter:
    def name(self) -> str: ...
    def shape(self) -> List[int]: ...
    def to_list(self) -> List[float]: ...
    def grad(self) -> Optional[List[float]]: ...
    def zero_grad(self) -> None: ...
    def __repr__(self) -> str: ...

class Linear:
    def __init__(self, in_features: int, out_features: int, bias: bool = True) -> None: ...
    def forward(self, input: Variable) -> Variable: ...
    def parameters(self) -> List[Parameter]: ...
    def in_features(self) -> int: ...
    def out_features(self) -> int: ...

class MSELoss:
    def __init__(self) -> None: ...
    def forward(self, pred: Variable, target: Variable) -> Variable: ...
    def parameters(self) -> List[Parameter]: ...

class SGD:
    def __init__(self, params: List[Parameter], lr: float, momentum: float = 0.0) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class Adam:
    def __init__(self, params: List[Parameter], lr: float) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

# Element-wise
def add(a: Tensor, b: Tensor) -> Tensor: ...
def mul(a: Tensor, b: Tensor) -> Tensor: ...
def sub(a: Tensor, b: Tensor) -> Tensor: ...
def div(a: Tensor, b: Tensor) -> Tensor: ...
def add_scalar(tensor: Tensor, scalar: float) -> Tensor: ...
def mul_scalar(tensor: Tensor, scalar: float) -> Tensor: ...

# Matrix
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def transpose(tensor: Tensor) -> Tensor: ...
def reshape(tensor: Tensor, shape: List[int]) -> Tensor: ...

# Reductions
def sum(tensor: Tensor) -> float: ...
def mean(tensor: Tensor) -> float: ...

# Activations
def relu(tensor: Tensor) -> Tensor: ...
def sigmoid(tensor: Tensor) -> Tensor: ...
def tanh(tensor: Tensor) -> Tensor: ...
def gelu(tensor: Tensor) -> Tensor: ...
def leaky_relu(tensor: Tensor, alpha: float) -> Tensor: ...
def elu(tensor: Tensor, alpha: float) -> Tensor: ...
def selu(tensor: Tensor) -> Tensor: ...
def swish(tensor: Tensor) -> Tensor: ...
def mish(tensor: Tensor) -> Tensor: ...
def softplus(tensor: Tensor) -> Tensor: ...
def softsign(tensor: Tensor) -> Tensor: ...
def softmax(tensor: Tensor, dim: int) -> Tensor: ...

# Losses (tensor level)
def mse_loss(pred: Tensor, target: Tensor) -> float: ...
def l1_loss(pred: Tensor, target: Tensor) -> float: ...
def smooth_l1_loss(pred: Tensor, target: Tensor, beta: float) -> float: ...
def binary_cross_entropy_loss(pred: Tensor, target: Tensor, epsilon: float) -> float: ...
def cross_entropy_loss(pred: Tensor, target: Tensor, epsilon: float) -> float: ...

# Optimizer updates (low-level)
def sgd_update(params: Tensor, gradients: Tensor, lr: float) -> Tensor: ...
def sgd_momentum_update(params: Tensor, gradients: Tensor, velocity: Tensor, lr: float, momentum: float) -> Tuple[Tensor, Tensor]: ...
def adam_update(params: Tensor, gradients: Tensor, m: Tensor, v: Tensor, lr: float, beta1: float, beta2: float, eps: float, t: int) -> Tuple[Tensor, Tensor, Tensor]: ...
def adamw_update(params: Tensor, gradients: Tensor, m: Tensor, v: Tensor, lr: float, beta1: float, beta2: float, eps: float, wd: float, t: int) -> Tuple[Tensor, Tensor, Tensor]: ...

# Broadcast
def add_broadcast(a: Tensor, b: Tensor) -> Tensor: ...
def mul_broadcast(a: Tensor, b: Tensor) -> Tensor: ...
def sub_broadcast(a: Tensor, b: Tensor) -> Tensor: ...
def div_broadcast(a: Tensor, b: Tensor) -> Tensor: ...

# SIMD-named (parallel + auto-vec)
def add_simd(a: Tensor, b: Tensor) -> Tensor: ...
def mul_simd(a: Tensor, b: Tensor) -> Tensor: ...
def relu_simd(tensor: Tensor) -> Tensor: ...
def mul_scalar_simd(tensor: Tensor, scalar: float) -> Tensor: ...
def fused_multiply_add(a: Tensor, b: Tensor, c: Tensor) -> Tensor: ...

# Data
def load_csv(path: str, has_header: bool, delimiter: str) -> Tensor: ...
def normalize(tensor: Tensor) -> Tuple[Tensor, float, float]: ...
def create_batches(data: Tensor, batch_size: int, drop_last: bool) -> List[Tensor]: ...
def shuffle_indices(n: int) -> List[int]: ...
def train_val_test_split(data: Tensor, train: float, val: float, shuffle: bool) -> Tuple[Tensor, Tensor, Tensor]: ...